version: '3.8'

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx_container
    volumes:
      - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - web_nw

  python:
    restart: always
    build:
      context: .
      dockerfile: services.python.Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
    env_file: .env.sample
    volumes:
      - ./logs/python:/logs

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env.db-sample
    networks:
      - db_nw
    volumes:
      - ./services/mysql/config/log.cnf:/etc/mysql/conf.d/log.cnf
      - ./logs/mysql:/var/log/mysql
      - db-store:/var/lib/mysql

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  db-store: